---

- hosts: dbserver
  remote_user: azureuser
  become_user: root
  
  tasks:

    - name: Load in project specific vars
      include_vars:
        file: "main.yml"
        name: variable

    - name: Install MySQL
      apt:
        name: ['mysql-server','mysql-client','python-mysqldb']
        state: latest
      register: install_package
      
    - debug: 
        msg: '{{install_package}}'
    
    - name: config_mysql
      command: sed -i 's/bind-address.*/bind-address=10.0.2.30/g' /etc/mysql/mysql.conf.d/mysqld.cnf
      
    - name: restart mysql
      service:
        name: mysql
        state: restarted
        enabled: yes
      when: install_package.changed
    
    - name: Create database
      community.mysql.mysql_db:
        name: "{{variable.db_name}}"
        login_user: 'root'
        login_password: "{{variable.db_password}}"
        state: present
    
    - name: Create user for the database
      community.mysql.mysql_user:  
        name: "{{variable.db_user}}"  
        password: "{{variable.db_password}}"
        priv: '*.*:ALL,GRANT'
        login_user: 'root'
        login_password: "{{variable.db_password}}"
        state: present
    
    - name: Simple select query to acme db
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{variable.db_password}}"
        query: GRANT ALL PRIVILEGES ON mediadb.* TO mediadbuser@'10.0.1.5' IDENTIFIED BY 'Password1234!'
        