---
# tasks file for app
# - apt_repository:
#     repo: ppa:nginx/stable
# - name: Update and upgrade apt packages
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400
# - name: adding license server
#   lineinfile: dest=/etc/apt/sources.list line="deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main"
# - name: adding license server
#   lineinfile: dest=/etc/apt/sources.list line="deb-src http://ppa.launchpad.net/ondrej/php/ubuntu bionic main"
- name: Install mediawiki dependencies
  apt:
    name: ['apache2', 'php', 'php-mysql', 'libapache2-mod-php', 'php-xml', 'php-mbstring']
    state: latest
  notify: restart apache2
- name: Download Mediawiki software
  get_url:
    url: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-core-1.34.4.tar.gz
    dest: /tmp/mediawiki-core-1.34.4.tar.gz
  register: download_wiki
- name: Create work directory 
  file:
      path: /var/lib/mediawiki
      state: directory
      owner: root
      group: root
      mode: '0775'
- name: Extracting Mediawiki software
  command: tar -xzf  /tmp/mediawiki-core-1.34.4.tar.gz -C /var/lib/mediawiki
- name: linking webroot
  command: ln -sf /var/lib/mediawiki/mediawiki-1.34.4 /var/www/html/mediawiki
- name: Configure local settings network
  template:
    src: LocalSettings.j2
    dest: "/var/www/html/mediawiki/LocalSettings.php"
    owner: root
    group: root
    force: yes
    mode: 0644
