- name: Install MySQL
  apt:
    name: ['mysql-server','mysql-client','python-mysqldb']
    state: latest
  notify: restart mysql

- name: Create database
  community.mysql.mysql_db:
    name: 'mediadb'
    state: present

- name: Create user for the database
  community.mysql.mysql_user:  
    name: 'mediadbuser'    
    password: 'Password1234!'
    priv: '*.*:ALL,GRANT'
    state: present

    



