- name: Install MySQL
  apt:
    name: ['mysql-server','mysql-client','python-mysqldb']
    state: latest
  notify: restart mysql

- name: Install requests python package
  pip:
    name: requests
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Create database
  community.mysql.mysql_db:
    name: 'mediadb'
    state: present

- name: Create user for the database
  community.mysql.mysql_user:  
    name: 'mediadbuser'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: 'Password1234!'
    priv: '*.*:ALL,GRANT'
    state: present
    



